Feature
renercrows/Milestone1 pull request #1
Opened 2022-07-01 17:37 UTC by renercrows

2022-07-01 21:14 UTC, DeliceLydia requested changes
## Hi @renercrows, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there! Kudos to the:
- good looking UI
- Followed git workflow


## Suggested changes
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-01 21:14 UTC, DeliceLydia commented on README.md
> +- etc
- [ ] The README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-07-01 21:14 UTC, DeliceLydia commented on README.md
> +Feel free to check the [issues page](../../issues/).
- [ ] Please deploy your page on GitHub and add a link in the README

2022-07-01 21:14 UTC, DeliceLydia commented on about.html
> +    </footer>
- [ ] I suggest you give similar spacing, borders, shadows, and paddings to the original design.
![design](https://user-images.githubusercontent.com/44745855/176967944-5848d9d3-028c-4f73-bce4-f23f4483e57f.png)

2022-07-01 21:14 UTC, DeliceLydia commented on script.js
> +];
- [ ] Featured speakers section spacing, borders, shadows, and paddings than the original design
![speaker](https://user-images.githubusercontent.com/44745855/176968385-74fde9c7-48a6-45a7-8267-0e77387f94b4.png)

2022-07-02 00:30 UTC, andersonlebon approved these changes
## Hi @renercrows 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-02 00:45 UTC, merged